fix: getListItemIterator causes typescript issue when using a Driver with inner parts declaration
Summary:
When getListItemIterator is used with drivers with inner parts such as CheckboxDriver, TypeScript error TS2345 (type incompatibility) occurs.  This PR fixes it by relaxing some type restriction.